# Generated by Django 3.1.7 on 2021-04-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20210417_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
